
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shixun
    username: root
    password: hermione1212

  redis:
    host: localhost
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
server:
  port: 8080